### ISSUE TITLE
Framework Tasks

### ISSUE THREAD

**Issue by shellscape** [shellscape/webpack-plugin-serve#116]
Created this issue to track and organize commits on mater that needs to be ported over to the framework branch:

- [x] fix: handle bad filePath from webpack (#114) _webpack specific_
- [x] fix: handle a potential uncaughtException (#113)
- [x] fix: missing progress, status. fixes #109 (f4a6485c5c2bb4c0edd2cb42dc851adc681a5768)
- [x] fix: exclude tslint.json from package (e311a75869ca0ca5bfcf0dc474eee909f2b4c28e)
- [x] fix: add typings directory to package (51f93fda3b3219d712f897f8a97ef3a383019410)
- [x] refactor: clean up typescript improvements, npm audit alerts (210d01acd960c81129b97992963e880d6e6a5ceb)
- [x] fix(ts): Add typescript usage test, fix typescript errors (#111)
- [x] chore: code style (a098809ea7f6f019577224f20e20b06a17157e0e)
- [x] docs: add note for build errors and hmr (027c678db2679db8618154258ae9f2eb1fe1a5e2)
- [x] fix: allow HMR when build contains warnings (#106)
- [x] feat: add waitForBuild option (#102) 
- [x] docs(recipes): add ssr recipe [fixes #54] (#99)
- [x] fix: flaky silent logs in client (1dbf4aa6e2acc789c8e5c312e270c7e6345b0e52)
- [x] fix: strip accept header when using history-api-fallback (#98)
- [x] feat: add client.silent option (#97)
- [x] fix: undefineds in client. fixes #78, #95 (ac542c016801de11bd4e15196a8f6883fcdbf3e4)
- [x] chore(meta): Add support for node 10.15.0 and above in 'engines' (#93)
- [x] sync docs and recipes

**Comment by shellscape** [comment]
`master` merged with `refactor/framework`. framework development can continue 🎉
